# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sami_rag_client.api.orchestrator_api import ORCHESTRATORApi


class TestORCHESTRATORApi(unittest.TestCase):
    """ORCHESTRATORApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ORCHESTRATORApi()

    def tearDown(self) -> None:
        pass

    def test_rag_query(self) -> None:
        """Test case for rag_query

        Rag Query
        """
        pass


if __name__ == '__main__':
    unittest.main()
