# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sami_rag_client.models.ingest_sync_response import IngestSyncResponse

class TestIngestSyncResponse(unittest.TestCase):
    """IngestSyncResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IngestSyncResponse:
        """Test IngestSyncResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IngestSyncResponse`
        """
        model = IngestSyncResponse()
        if include_optional:
            return IngestSyncResponse(
                source_adapter = '',
                synced_count = 56,
                accepted = 56,
                quarantined = 56,
                rejected = 56,
                accepted_doc_ids = [
                    ''
                    ],
                quarantined_doc_ids = [
                    ''
                    ],
                rejected_doc_ids = [
                    ''
                    ]
            )
        else:
            return IngestSyncResponse(
                source_adapter = '',
                synced_count = 56,
                accepted = 56,
                quarantined = 56,
                rejected = 56,
                accepted_doc_ids = [
                    ''
                    ],
                quarantined_doc_ids = [
                    ''
                    ],
                rejected_doc_ids = [
                    ''
                    ],
        )
        """

    def testIngestSyncResponse(self):
        """Test IngestSyncResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
