# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sami_rag_client.models.health_response_model import HealthResponseModel

class TestHealthResponseModel(unittest.TestCase):
    """HealthResponseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HealthResponseModel:
        """Test HealthResponseModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HealthResponseModel`
        """
        model = HealthResponseModel()
        if include_optional:
            return HealthResponseModel(
                status = '',
                version = '',
                model_loaded = True,
                device = '',
                uptime_seconds = 1.337,
                total_requests = 56,
                avg_latency_ms = 1.337
            )
        else:
            return HealthResponseModel(
                status = '',
                version = '',
                model_loaded = True,
                device = '',
                uptime_seconds = 1.337,
                total_requests = 56,
                avg_latency_ms = 1.337,
        )
        """

    def testHealthResponseModel(self):
        """Test HealthResponseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
