# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sami_rag_client.models.rag_query_response import RagQueryResponse

class TestRagQueryResponse(unittest.TestCase):
    """RagQueryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RagQueryResponse:
        """Test RagQueryResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RagQueryResponse`
        """
        model = RagQueryResponse()
        if include_optional:
            return RagQueryResponse(
                request_id = '',
                tenant_id = '',
                app_id = '',
                query = '',
                answer = '',
                context_docs = [
                    ''
                    ],
                defense = sami_rag_client.models.defense_summary.DefenseSummary(
                    applied = True, 
                    success = True, 
                    error = '', 
                    removed_indices = [
                        56
                        ], 
                    risk_scores = [
                        1.337
                        ], 
                    processing_time_ms = 1.337, ),
                policy_enforcement = sami_rag_client.models.policy_enforcement_summary.PolicyEnforcementSummary(
                    policy_mode = '', 
                    blocked = True, 
                    reason = '', 
                    retriever_backend = '', 
                    legacy_backfill_required = True, 
                    legacy_backfill_completed = True, 
                    risk_acknowledged_at = '', )
            )
        else:
            return RagQueryResponse(
                request_id = '',
                tenant_id = '',
                app_id = '',
                query = '',
                answer = '',
                context_docs = [
                    ''
                    ],
                defense = sami_rag_client.models.defense_summary.DefenseSummary(
                    applied = True, 
                    success = True, 
                    error = '', 
                    removed_indices = [
                        56
                        ], 
                    risk_scores = [
                        1.337
                        ], 
                    processing_time_ms = 1.337, ),
                policy_enforcement = sami_rag_client.models.policy_enforcement_summary.PolicyEnforcementSummary(
                    policy_mode = '', 
                    blocked = True, 
                    reason = '', 
                    retriever_backend = '', 
                    legacy_backfill_required = True, 
                    legacy_backfill_completed = True, 
                    risk_acknowledged_at = '', ),
        )
        """

    def testRagQueryResponse(self):
        """Test RagQueryResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
