# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sami_rag_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_file_sanitization(self) -> None:
        """Test case for file_sanitization

        Replace content in uploaded files
        """
        pass

    def test_multimodal_chat(self) -> None:
        """Test case for multimodal_chat

        Multimodal chat completions
        """
        pass


if __name__ == '__main__':
    unittest.main()
