# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sami_rag_client.api.sami_api import SAMIApi


class TestSAMIApi(unittest.TestCase):
    """SAMIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SAMIApi()

    def tearDown(self) -> None:
        pass

    def test_approve_quarantine_doc(self) -> None:
        """Test case for approve_quarantine_doc

        Quarantine
        """
        pass

    def test_ingest_commit(self) -> None:
        """Test case for ingest_commit

        Data Ingestion
        """
        pass

    def test_ingest_sync(self) -> None:
        """Test case for ingest_sync

        Ingest Sync
        """
        pass

    def test_reject_quarantine_doc(self) -> None:
        """Test case for reject_quarantine_doc

        Reject Quarantine
        """
        pass


if __name__ == '__main__':
    unittest.main()
