# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sami_rag_client.api.defender_api import DEFENDERApi


class TestDEFENDERApi(unittest.TestCase):
    """DEFENDERApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DEFENDERApi()

    def tearDown(self) -> None:
        pass

    def test_defend_v1_defend_post(self) -> None:
        """Test case for defend_v1_defend_post

        Defend
        """
        pass


if __name__ == '__main__':
    unittest.main()
