# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sami_rag_client.models.policy_enforcement_summary import PolicyEnforcementSummary

class TestPolicyEnforcementSummary(unittest.TestCase):
    """PolicyEnforcementSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyEnforcementSummary:
        """Test PolicyEnforcementSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyEnforcementSummary`
        """
        model = PolicyEnforcementSummary()
        if include_optional:
            return PolicyEnforcementSummary(
                policy_mode = '',
                blocked = True,
                reason = '',
                retriever_backend = '',
                legacy_backfill_required = True,
                legacy_backfill_completed = True,
                risk_acknowledged_at = ''
            )
        else:
            return PolicyEnforcementSummary(
                policy_mode = '',
                blocked = True,
                reason = '',
        )
        """

    def testPolicyEnforcementSummary(self):
        """Test PolicyEnforcementSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
