# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sami_rag_client.models.quarantine_review_request import QuarantineReviewRequest

class TestQuarantineReviewRequest(unittest.TestCase):
    """QuarantineReviewRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuarantineReviewRequest:
        """Test QuarantineReviewRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuarantineReviewRequest`
        """
        model = QuarantineReviewRequest()
        if include_optional:
            return QuarantineReviewRequest(
                reason = '',
                retriever_backend = '',
                incident_id = '',
                bucket = '',
                data_source_id = ''
            )
        else:
            return QuarantineReviewRequest(
        )
        """

    def testQuarantineReviewRequest(self):
        """Test QuarantineReviewRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
