# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from sami_rag_client.models.document_score_model import DocumentScoreModel
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DefendResponseModel(BaseModel):
    """
    Response model for /v1/defend endpoint.
    """ # noqa: E501
    success: StrictBool
    clean_documents: List[StrictStr]
    kept_indices: List[StrictInt]
    removed_indices: List[StrictInt]
    document_scores: List[DocumentScoreModel]
    stats: Dict[str, Any]
    request_id: Optional[StrictStr] = None
    processing_time_ms: Union[StrictFloat, StrictInt]
    error: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["success", "clean_documents", "kept_indices", "removed_indices", "document_scores", "stats", "request_id", "processing_time_ms", "error"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DefendResponseModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in document_scores (list)
        _items = []
        if self.document_scores:
            for _item_document_scores in self.document_scores:
                if _item_document_scores:
                    _items.append(_item_document_scores.to_dict())
            _dict['document_scores'] = _items
        # set to None if request_id (nullable) is None
        # and model_fields_set contains the field
        if self.request_id is None and "request_id" in self.model_fields_set:
            _dict['request_id'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DefendResponseModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "clean_documents": obj.get("clean_documents"),
            "kept_indices": obj.get("kept_indices"),
            "removed_indices": obj.get("removed_indices"),
            "document_scores": [DocumentScoreModel.from_dict(_item) for _item in obj["document_scores"]] if obj.get("document_scores") is not None else None,
            "stats": obj.get("stats"),
            "request_id": obj.get("request_id"),
            "processing_time_ms": obj.get("processing_time_ms"),
            "error": obj.get("error")
        })
        return _obj


