# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class QuarantineReviewRequest(BaseModel):
    """
    QuarantineReviewRequest
    """ # noqa: E501
    reason: Optional[StrictStr] = Field(default=None, description="Reviewer reason for approve/reject action")
    retriever_backend: Optional[StrictStr] = None
    incident_id: Optional[StrictStr] = None
    bucket: Optional[StrictStr] = None
    data_source_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["reason", "retriever_backend", "incident_id", "bucket", "data_source_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of QuarantineReviewRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['reason'] = None

        # set to None if retriever_backend (nullable) is None
        # and model_fields_set contains the field
        if self.retriever_backend is None and "retriever_backend" in self.model_fields_set:
            _dict['retriever_backend'] = None

        # set to None if incident_id (nullable) is None
        # and model_fields_set contains the field
        if self.incident_id is None and "incident_id" in self.model_fields_set:
            _dict['incident_id'] = None

        # set to None if bucket (nullable) is None
        # and model_fields_set contains the field
        if self.bucket is None and "bucket" in self.model_fields_set:
            _dict['bucket'] = None

        # set to None if data_source_id (nullable) is None
        # and model_fields_set contains the field
        if self.data_source_id is None and "data_source_id" in self.model_fields_set:
            _dict['data_source_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of QuarantineReviewRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "reason": obj.get("reason"),
            "retriever_backend": obj.get("retriever_backend"),
            "incident_id": obj.get("incident_id"),
            "bucket": obj.get("bucket"),
            "data_source_id": obj.get("data_source_id")
        })
        return _obj


