# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RagQueryRequest(BaseModel):
    """
    Request body for RAG query.
    """ # noqa: E501
    query: StrictStr = Field(description="User query")
    top_k: Optional[Annotated[int, Field(le=100, strict=True, ge=1)]] = Field(default=10, description="Number of documents to retrieve (mock retriever)")
    channel: Optional[StrictStr] = Field(default=None, description="Channel identifier (web, api, mobile, etc.)")
    retriever_backend: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["query", "top_k", "channel", "retriever_backend"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RagQueryRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if channel (nullable) is None
        # and model_fields_set contains the field
        if self.channel is None and "channel" in self.model_fields_set:
            _dict['channel'] = None

        # set to None if retriever_backend (nullable) is None
        # and model_fields_set contains the field
        if self.retriever_backend is None and "retriever_backend" in self.model_fields_set:
            _dict['retriever_backend'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RagQueryRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "top_k": obj.get("top_k") if obj.get("top_k") is not None else 10,
            "channel": obj.get("channel"),
            "retriever_backend": obj.get("retriever_backend")
        })
        return _obj


