# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from sami_rag_client.models.defense_summary import DefenseSummary
from sami_rag_client.models.policy_enforcement_summary import PolicyEnforcementSummary
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RagQueryResponse(BaseModel):
    """
    Response body for RAG query.
    """ # noqa: E501
    request_id: StrictStr
    tenant_id: Optional[StrictStr]
    app_id: StrictStr
    query: StrictStr
    answer: StrictStr
    context_docs: List[StrictStr]
    defense: DefenseSummary
    policy_enforcement: PolicyEnforcementSummary
    __properties: ClassVar[List[str]] = ["request_id", "tenant_id", "app_id", "query", "answer", "context_docs", "defense", "policy_enforcement"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RagQueryResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of defense
        if self.defense:
            _dict['defense'] = self.defense.to_dict()
        # override the default output from pydantic by calling `to_dict()` of policy_enforcement
        if self.policy_enforcement:
            _dict['policy_enforcement'] = self.policy_enforcement.to_dict()
        # set to None if tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_id is None and "tenant_id" in self.model_fields_set:
            _dict['tenant_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RagQueryResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "request_id": obj.get("request_id"),
            "tenant_id": obj.get("tenant_id"),
            "app_id": obj.get("app_id"),
            "query": obj.get("query"),
            "answer": obj.get("answer"),
            "context_docs": obj.get("context_docs"),
            "defense": DefenseSummary.from_dict(obj["defense"]) if obj.get("defense") is not None else None,
            "policy_enforcement": PolicyEnforcementSummary.from_dict(obj["policy_enforcement"]) if obj.get("policy_enforcement") is not None else None
        })
        return _obj


